# Generated by Django 3.2.5 on 2022-01-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220101_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cartUser',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
